name: upload artifacts workflow
description: upload artifacts workflow
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: .
