name: serverless pr workflow
description: serverless pr workflow
runs:
  using: "composite"
  steps:
    # Make changes to pull request here

    - name: Create Pull Request
      uses: vsoch/pull-request-action@master
