name: serverless pr workflow
on:
  workflow_call:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
permissions: write-all
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create pull request
        uses: kuntrapakam/reusable-workflow/.github/actions/nestjs@main
