name: serverless pr workflow
on:
  workflow_call:
  push:
    branches:
      - main
permissions: write-all
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create pull request
        uses: ./actions/serverless@main
