name: serverless pr workflow
on:
  workflow_call:
    # inputs:
    #   GITHUB_TOKEN:
    #     required: true
    #     type: string
    #     description: git token
  workflow_dispatch:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
permissions: write-all
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create pull request
        uses: kuntrapakam/reusable-workflow/.github/actions/serverless@main
        # with:
        #   GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
